disabled_rules:
  - line_length
  - type_name
  - switch_case_alignment
opt_in_rules:
  - empty_count
  - explicit_init
included:
  - "Astrix/Sources/**"
  - "FinderTools/**"
excluded:
  - Carthage
  - Pods
